# Generated by Django 3.2.6 on 2021-12-05 22:40
import uuid

from django.db import migrations, models

from home.models import Room


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    def gen_uuid(apps, schema_editor):
        for row in Room.objects.all():
            row.slug = uuid.uuid4()
            row.save()

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default=uuid.uuid4),
            preserve_default=True,
        ),
        migrations.RunPython(gen_uuid),

        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
